import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AccountProvider } from "@/contexts/AccountContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen`}
      >
        <AccountProvider>
          {children}
        </AccountProvider>
        <script
          dangerouslySetInnerHTML={{
            __html: `
              // Set theme before page loads to prevent flash
              (function() {
                const theme = localStorage.getItem('theme') || 'dark';
                document.documentElement.className = theme;
              })();
            `,
          }}
        />
      </body>
    </html>
  );
}
